name: pyinstaller-build
on:
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.runs-on }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
    - name: Build with pyinstaller
      run: |
        pyinstaller --onefile --windowed resize.spec
    - name: Upload build (ubuntu-latest)
      uses: actions/upload-artifact@v1
      with:
        name: resize-linux
        path: dist/resize
      if: matrix.runs-on == 'ubuntu-latest'
    - name: Upload build (macOS-latest)
      uses: actions/upload-artifact@v1
      with:
        name: resize-macos
        path: dist/resize.app
      if: matrix.runs-on == 'macOS-latest'
    - name: Upload build (windows-latest)
      uses: actions/upload-artifact@v1
      with:
        name: resize-windows
        path: dist/resize.exe
      if: matrix.runs-on == 'windows-latest'
